openapi: 3.0.0
info:
  version: "1.0.0"
  title: The API school
paths:
  /groups/avg-grades{group-num}:
    get:
      summary: Получение средних оценок учеников в указанном классе
      parameters:
        - in: path
          name: group-num
          required: true
          schema:
            type: integer
          description: Идентификатор класса, для которого нужно получить средние оценки
      responses:
        '200':
          description: Успешный запрос
          content:
            application/json:
              example:
                - firstName: Иван
                  lastName: Петров
                  aveGrade: 4.50
                - firstName: Ольга
                  lastName: Сидорова
                  aveGrade: 4.00
        '404':
          description: Студенты не найдены

  /groups/avg-grades/{group-num}/subjects:
    put:
      summary: Изменение оценки конкретного ученика по ФИ, классу и конкретному предмету
      parameters:
        - in: path
          name: group-num
          required: true
          schema:
            type: integer
          description: Идентификатор класса
        - in: query
          name: subject
          schema:
            type: string
          description: Название предмета, например, "математика"
        - in: query
          name: first-name
          schema:
            type: string
          description: Имя ученика, например, "Иван"
        - in: query
          name: last-name
          schema:
            type: string
          description: Фамилия ученика, например, "Петров"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                grade:
                  type: number
                  format: integer
                  example: 4
      responses:
        '200':
          description: Оценка ученика успешно обновлена
        '404':
          description: Ученик с указанными ФИ, класс или предмет не найдены
        '400':
          description: Неверный формат запроса или неверные данные